name: Teste Pipeline

on:
  push:
    branches:
      - feature/sonarless
  pull_request:
    branches:
      - feature/sonarless

jobs:
  Sonarless-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean compile -f petshare-backend/pom.xml

      - name: Create SonarQube Properties File
        run: |
          echo "sonar.projectKey=petShare-api" > sonar-project.properties
          echo "sonar.sources=petshare-backend/src" >> sonar-project.properties
          echo "sonar.java.binaries=petshare-backend/target/classes" >> sonar-project.properties

      - name: Sonarless Scan
        uses: gitricko/sonarless@v1.2
        with:
          sonar-project-name: 'petShare-api'
          sonar-project-key: 'petShare-api'
          sonar-source-path: 'petshare-backend/src'
