name: Security SAST Scan

on:
  pull_request: {}  
  workflow_dispatch: {}  
  push:
    branches: ["feature/SAST"] 

jobs:
  semgrep_scan:
    name: Semgrep SAST Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      security-events: write  
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Run Semgrep Security Scan
        run: semgrep scan --sarif --config auto ./petshare-backend/src > semgrep-results.sarif

      - name: Save SARIF results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-scan-results
          path: semgrep-results.sarif

      - name: Upload SARIF result to the GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
        if: always()
